# Generated by Django 3.1.3 on 2021-02-03 12:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigController',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='main_config_controller', max_length=100, null=True, unique=True)),
                ('competitions_page_refresh_time', models.IntegerField(default=15000)),
                ('competitions_bg_tasks', models.IntegerField(default=900)),
                ('competitions_dummy_data', models.BooleanField(default=False)),
                ('cod_url_warzone_stats', models.CharField(max_length=500, null=True, unique=True)),
                ('cod_url_warzone_matches', models.CharField(max_length=500, null=True, unique=True)),
                ('cod_x_rapidapi_key', models.CharField(max_length=250, null=True, unique=True)),
                ('cod_x_rapidapi_host', models.CharField(max_length=250, null=True, unique=True)),
                ('twitch_api_verfication_client_id', models.CharField(max_length=100, null=True, unique=True)),
                ('twitch_api_verfication_client_secret', models.CharField(max_length=100, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'ConfigController',
                'verbose_name_plural': 'ConfigControllers',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activision_tag', models.CharField(max_length=100, null=True, unique=True)),
                ('kda', models.FloatField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('total_kills', models.IntegerField(default=0)),
                ('last_ten_matches', models.JSONField(blank=True, default=dict)),
                ('last_calculated_matches', models.JSONField(blank=True, default=dict)),
                ('avg_kills_over_last_ten_matches', models.FloatField(default=0)),
                ('avg_kda_over_last_ten_matches', models.FloatField(default=0)),
                ('avg_damage_over_last_ten_matches', models.FloatField(default=0)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='StaffCustomCompetition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_name', models.CharField(max_length=150, null=True, unique=True)),
                ('competition_description', models.TextField(default='')),
                ('competition_type', models.CharField(choices=[('SQUADS', 'SQUADS'), ('TRIOS', 'TRIOS'), ('DUOS', 'DUOS'), ('SOLOS', 'SOLOS')], max_length=6)),
                ('competition_banner', models.URLField(default='https://cdn1.dotesports.com/wp-content/uploads/2019/12/16125403/cod38.jpg', max_length=1000)),
                ('total_teams_allowed_to_compete', models.IntegerField(default=30, null=True)),
                ('discord_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('instagram_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('facebook_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('twitter_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('twitch_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('cod_kd_maximum_per_player_verification', models.FloatField(default=3, verbose_name='Account Verification: KD maximum per player (Default = 3)')),
                ('cod_kd_minimum_per_player_verification', models.FloatField(default=1, verbose_name='Account Verification: KD minimum per player (Default = 1)')),
                ('cod_verification_total_games_played', models.IntegerField(default=100, verbose_name='Account Verification: Total amount of matches needed to verify account (Default = 100 games)')),
                ('cod_verification_total_time_played', models.IntegerField(default=5, verbose_name='Account Verification: Total amount of time played to verify account (Default = 5 days)')),
                ('number_of_matches_to_count_points', models.IntegerField(default=5)),
                ('points_per_kill', models.IntegerField(default=1)),
                ('points_per_first_place', models.IntegerField(default=10, verbose_name='Points for placing - 1st Place')),
                ('points_per_second_place', models.IntegerField(default=5, verbose_name='Points for placing - 2nd Place')),
                ('points_per_third_place', models.IntegerField(default=3, verbose_name='Points for placing - 3rd Place')),
                ('start_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('end_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('competition_started', models.BooleanField(default=False)),
                ('competition_status', models.IntegerField(default=3)),
                ('email_job_created', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CustomCompetition',
                'verbose_name_plural': 'CustomCompetitions',
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100, null=True, unique=True)),
                ('team_type', models.CharField(choices=[('SQUAD', 'squad'), ('TRIOS', 'trios'), ('DUOS', 'duos'), ('SOLOS', 'solos')], default='SQUAD', max_length=5)),
                ('cummulative_kd', models.FloatField(default=0)),
                ('total_wins', models.IntegerField(default=0)),
                ('total_kills', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('profiles', models.ManyToManyField(to='core.Profile')),
            ],
            options={
                'verbose_name': 'Teams',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='StaffCustomTeams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100, null=True, unique=True)),
                ('team_captain_email', models.EmailField(max_length=254, null=True)),
                ('team_banner', models.URLField(default='https://play-lh.googleusercontent.com/r2-_2oE9tU_46_n4GIC21PmqNIqPMoQNRPhfVNnK1v8hmDfA_yLuRwCy_E1cf5Wh4oM', max_length=1000)),
                ('team_twitch_stream_user', models.CharField(blank=True, max_length=150, null=True)),
                ('player_1', models.CharField(blank=True, max_length=100, null=True)),
                ('player_1_id_type', models.CharField(choices=[('battle', 'Battlenet ID'), ('psn', 'Psnet ID'), ('xbl', 'XboxLive ID')], default='battle', max_length=10)),
                ('player_2', models.CharField(blank=True, max_length=100, null=True)),
                ('player_2_id_type', models.CharField(choices=[('battle', 'Battlenet ID'), ('psn', 'Psnet ID'), ('xbl', 'XboxLive ID')], default='battle', max_length=10)),
                ('player_3', models.CharField(blank=True, max_length=100, null=True)),
                ('player_3_id_type', models.CharField(choices=[('battle', 'Battlenet ID'), ('psn', 'Psnet ID'), ('xbl', 'XboxLive ID')], default='battle', max_length=10)),
                ('player_4', models.CharField(blank=True, max_length=100, null=True)),
                ('player_4_id_type', models.CharField(choices=[('battle', 'Battlenet ID'), ('psn', 'Psnet ID'), ('xbl', 'XboxLive ID')], default='battle', max_length=10)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('data_stats', models.JSONField(blank=True, default=dict)),
                ('data_stats_loaded', models.BooleanField(default=False)),
                ('data_to_render', models.JSONField(blank=True, default=dict)),
                ('score', models.IntegerField(default=0)),
                ('email_check_in_sent', models.BooleanField(default=False)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='core.staffcustomcompetition')),
            ],
            options={
                'verbose_name': 'CustomTeam',
                'verbose_name_plural': 'CustomTeams',
            },
        ),
    ]
