# Generated by Django 3.1.3 on 2020-12-18 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activision_tag', models.CharField(max_length=100, null=True, unique=True)),
                ('kda', models.FloatField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('total_kills', models.IntegerField(default=0)),
                ('last_ten_matches', models.JSONField(blank=True, default=dict)),
                ('last_calculated_matches', models.JSONField(blank=True, default=dict)),
                ('avg_kills_over_last_ten_matches', models.FloatField(default=0)),
                ('avg_kda_over_last_ten_matches', models.FloatField(default=0)),
                ('avg_damage_over_last_ten_matches', models.FloatField(default=0)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='StaffCustomCompetition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_name', models.CharField(max_length=150, null=True, unique=True)),
                ('points_per_kill', models.IntegerField(default=1)),
                ('points_per_first_place', models.IntegerField(blank=True)),
                ('points_per_second_place', models.IntegerField(blank=True)),
                ('points_per_third_place', models.IntegerField(blank=True)),
                ('created_by', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CustomCompetition',
                'verbose_name_plural': 'CustomCompetitions',
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100, null=True, unique=True)),
                ('team_type', models.CharField(choices=[('SQUAD', 'squad'), ('TRIOS', 'trios'), ('DUOS', 'duos'), ('SOLOS', 'solos')], default='SQUAD', max_length=5)),
                ('cummulative_kd', models.FloatField(default=0)),
                ('total_wins', models.IntegerField(default=0)),
                ('total_kills', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('profiles', models.ManyToManyField(to='core.Profile')),
            ],
            options={
                'verbose_name': 'Teams',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='StaffCustomTeams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_1', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('player_2', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('player_3', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('player_4', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('data_to_score', models.JSONField(blank=True, default=dict)),
                ('score', models.IntegerField(default=0)),
                ('team_name', models.CharField(max_length=100, null=True, unique=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.staffcustomcompetition')),
            ],
            options={
                'verbose_name': 'CustomTeam',
                'verbose_name_plural': 'CustomTeams',
            },
        ),
    ]
