# Generated by Django 3.1.3 on 2020-12-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffcustomteams',
            name='data_stats',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
