# Generated by Django 3.1.3 on 2021-02-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffcustomteams',
            name='player_1_id_type',
            field=models.CharField(choices=[('acti', 'Activision ID'), ('battle', 'Battlenet ID'), ('psn', 'Psnet ID'), ('xbl', 'XboxLive ID')], default='acti', max_length=10),
        ),
        migrations.AlterField(
            model_name='staffcustomteams',
            name='player_2_id_type',
            field=models.CharField(choices=[('acti', 'Activision ID'), ('battle', 'Battlenet ID'), ('psn', 'Psnet ID'), ('xbl', 'XboxLive ID')], default='acti', max_length=10),
        ),
        migrations.AlterField(
            model_name='staffcustomteams',
            name='player_3_id_type',
            field=models.CharField(choices=[('acti', 'Activision ID'), ('battle', 'Battlenet ID'), ('psn', 'Psnet ID'), ('xbl', 'XboxLive ID')], default='acti', max_length=10),
        ),
        migrations.AlterField(
            model_name='staffcustomteams',
            name='player_4_id_type',
            field=models.CharField(choices=[('acti', 'Activision ID'), ('battle', 'Battlenet ID'), ('psn', 'Psnet ID'), ('xbl', 'XboxLive ID')], default='acti', max_length=10),
        ),
    ]
