# Generated by Django 3.1.3 on 2021-01-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configcontroller',
            name='twitch_api_verfication_client_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='configcontroller',
            name='twitch_api_verfication_client_secret',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
