# Generated by Django 3.1.3 on 2020-12-18 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffcustomcompetition',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='staffcustomcompetition',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='staffcustomcompetition',
            name='points_per_first_place',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='staffcustomcompetition',
            name='points_per_second_place',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='staffcustomcompetition',
            name='points_per_third_place',
            field=models.IntegerField(default=1),
        ),
    ]
