# Generated by Django 3.1.3 on 2020-12-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_staffcustomteams_data_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffcustomteams',
            name='data_stats_loaded',
            field=models.BooleanField(default=False),
        ),
    ]
