# Generated by Django 3.1.3 on 2021-02-03 22:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210203_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffcustomteams',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffcustomteams',
            name='checked_in_url',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
