# Generated by Django 3.1.3 on 2020-12-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201218_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffcustomcompetition',
            name='competition_description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='staffcustomcompetition',
            name='competition_started',
            field=models.IntegerField(default=0),
        ),
    ]
