# Generated by Django 3.1.3 on 2021-01-23 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210123_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffcustomteams',
            old_name='team_twitch_link',
            new_name='team_twitch_stream_user',
        ),
    ]
