# Generated by Django 3.1.3 on 2021-01-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210123_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffcustomteams',
            name='player_1_id_type',
            field=models.CharField(choices=[('battle', 'Battlenet ID'), ('psn', 'Psnet ID'), ('xbl', 'XboxLive ID')], default='battle', max_length=10),
        ),
        migrations.AlterField(
            model_name='staffcustomteams',
            name='player_2_id_type',
            field=models.CharField(choices=[('battle', 'Battlenet ID'), ('psn', 'Psnet ID'), ('xbl', 'XboxLive ID')], default='battle', max_length=10),
        ),
        migrations.AlterField(
            model_name='staffcustomteams',
            name='player_3_id_type',
            field=models.CharField(choices=[('battle', 'Battlenet ID'), ('psn', 'Psnet ID'), ('xbl', 'XboxLive ID')], default='battle', max_length=10),
        ),
        migrations.AlterField(
            model_name='staffcustomteams',
            name='player_4_id_type',
            field=models.CharField(choices=[('battle', 'Battlenet ID'), ('psn', 'Psnet ID'), ('xbl', 'XboxLive ID')], default='battle', max_length=10),
        ),
    ]
