# Generated by Django 3.1.3 on 2021-02-03 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210203_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffcustomteams',
            old_name='checked_in_url',
            new_name='checked_in_uuid',
        ),
    ]
