# Generated by Django 3.1.3 on 2020-12-18 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201218_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffcustomcompetition',
            old_name='competition_started',
            new_name='competition_status',
        ),
    ]
