# Generated by Django 3.1.3 on 2020-12-31 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_staffcustomteams_data_stats_loaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffcustomteams',
            name='team_banner',
            field=models.URLField(default='https://play-lh.googleusercontent.com/r2-_2oE9tU_46_n4GIC21PmqNIqPMoQNRPhfVNnK1v8hmDfA_yLuRwCy_E1cf5Wh4oM', max_length=1000),
        ),
    ]
