# Generated by Django 3.1.3 on 2021-02-04 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210203_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='configcontroller',
            name='competition_email_active',
            field=models.BooleanField(default=True),
        ),
    ]
