# Generated by Django 3.1.3 on 2021-01-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210125_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configcontroller',
            name='competitions_bg_tasks',
            field=models.IntegerField(default=900),
        ),
        migrations.AlterField(
            model_name='configcontroller',
            name='competitions_page_refresh_time',
            field=models.IntegerField(default=15000),
        ),
    ]
