# Generated by Django 3.1.3 on 2021-01-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_staffcustomteams_team_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffcustomteams',
            name='player_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staffcustomteams',
            name='player_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staffcustomteams',
            name='player_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staffcustomteams',
            name='player_4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
