# Generated by Django 3.1.3 on 2020-12-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201218_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffcustomcompetition',
            name='competition_ready',
            field=models.IntegerField(default=0),
        ),
    ]
