# Generated by Django 3.1.3 on 2020-12-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_staffcustomcompetition_competition_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffcustomcompetition',
            name='competition_ready',
            field=models.BooleanField(default=False),
        ),
    ]
