# Generated by Django 3.1.3 on 2021-01-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210125_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffcustomcompetition',
            name='cod_kd_limit_per_player_verification',
            field=models.FloatField(default=3),
        ),
    ]
