# Generated by Django 3.1.3 on 2020-12-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201218_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigController',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitions_page_refresh_time', models.IntegerField(default=5000)),
                ('competitions_bg_tasks', models.IntegerField(default=100)),
            ],
            options={
                'verbose_name': 'ConfigController',
                'verbose_name_plural': 'ConfigControllers',
            },
        ),
        migrations.AlterField(
            model_name='staffcustomcompetition',
            name='competition_status',
            field=models.IntegerField(default=3),
        ),
    ]
