# Generated by Django 3.1.3 on 2021-01-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_staffcustomcompetition_cod_kd_limit_per_player_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffcustomcompetition',
            name='cod_kd_limit_per_player_verification',
            field=models.FloatField(default=3, verbose_name='Account Verification: KD limit per player. Leave default for open KD tournament (Default = 3)'),
        ),
        migrations.AlterField(
            model_name='staffcustomcompetition',
            name='cod_verification_total_games_played',
            field=models.IntegerField(default=100, verbose_name='Account Verification: Total amount of matches needed to verify account (Default = 100 games)'),
        ),
        migrations.AlterField(
            model_name='staffcustomcompetition',
            name='cod_verification_total_time_played',
            field=models.IntegerField(default=5, verbose_name='Account Verification: Total amount of time played to verify account (Default = 5 days)'),
        ),
        migrations.AlterField(
            model_name='staffcustomcompetition',
            name='points_per_first_place',
            field=models.IntegerField(default=10, verbose_name='Points for placing - 1st Place'),
        ),
        migrations.AlterField(
            model_name='staffcustomcompetition',
            name='points_per_second_place',
            field=models.IntegerField(default=5, verbose_name='Points for placing - 2nd Place'),
        ),
        migrations.AlterField(
            model_name='staffcustomcompetition',
            name='points_per_third_place',
            field=models.IntegerField(default=3, verbose_name='Points for placing - 3rd Place'),
        ),
    ]
