# Generated by Django 3.1.3 on 2021-02-05 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_competitioncommunicationemails_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitioncommunicationemails',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='core.staffcustomcompetition'),
        ),
        migrations.AlterField(
            model_name='competitioncommunicationemails',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
