# Generated by Django 3.1.3 on 2021-01-27 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210127_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffcustomcompetition',
            old_name='competition_ready',
            new_name='competition_started',
        ),
    ]
