# Generated by Django 3.1.3 on 2021-02-05 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210205_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitioncommunicationemails',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
