# Generated by Django 3.1.3 on 2020-12-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_configcontroller_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='configcontroller',
            name='competitions_dummy_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='configcontroller',
            name='name',
            field=models.CharField(default='main_config_controller', max_length=100, null=True, unique=True),
        ),
    ]
