# Generated by Django 3.1.3 on 2021-01-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210127_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffcustomcompetition',
            name='cod_kd_limit_per_player_verification',
        ),
        migrations.AddField(
            model_name='staffcustomcompetition',
            name='cod_kd_maximum_per_player_verification',
            field=models.FloatField(default=3, verbose_name='Account Verification: KD maximum per player(Default = 3)'),
        ),
        migrations.AddField(
            model_name='staffcustomcompetition',
            name='cod_kd_minimum_per_player_verification',
            field=models.FloatField(default=1, verbose_name='Account Verification: KD minimum per player(Default = 1)'),
        ),
    ]
