# Generated by Django 3.1.3 on 2020-12-21 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201220_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffcustomcompetition',
            name='competition_banner',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
