# Generated by Django 3.1.3 on 2021-02-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_competitioncommunicationemails_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='profiles',
        ),
        migrations.AlterModelOptions(
            name='competitioncommunicationemails',
            options={'verbose_name': 'Competition Communication', 'verbose_name_plural': 'Competition Communications'},
        ),
        migrations.AlterModelOptions(
            name='configcontroller',
            options={'verbose_name': 'Application Configuration', 'verbose_name_plural': 'Application Configuration'},
        ),
        migrations.AlterModelOptions(
            name='staffcustomcompetition',
            options={'verbose_name': 'Custom Competition', 'verbose_name_plural': 'Custom Competitions'},
        ),
        migrations.AlterModelOptions(
            name='staffcustomteams',
            options={'verbose_name': 'Custom Team', 'verbose_name_plural': 'Custom Teams'},
        ),
        migrations.AddField(
            model_name='staffcustomcompetition',
            name='competition_is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='staffcustomteams',
            name='player_1_id_type',
            field=models.CharField(choices=[('battle', 'Battlenet ID'), ('psn', 'Psnet ID'), ('xbl', 'XboxLive ID')], default='battle', max_length=10),
        ),
        migrations.AlterField(
            model_name='staffcustomteams',
            name='player_2_id_type',
            field=models.CharField(choices=[('battle', 'Battlenet ID'), ('psn', 'Psnet ID'), ('xbl', 'XboxLive ID')], default='battle', max_length=10),
        ),
        migrations.AlterField(
            model_name='staffcustomteams',
            name='player_3_id_type',
            field=models.CharField(choices=[('battle', 'Battlenet ID'), ('psn', 'Psnet ID'), ('xbl', 'XboxLive ID')], default='battle', max_length=10),
        ),
        migrations.AlterField(
            model_name='staffcustomteams',
            name='player_4_id_type',
            field=models.CharField(choices=[('battle', 'Battlenet ID'), ('psn', 'Psnet ID'), ('xbl', 'XboxLive ID')], default='battle', max_length=10),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Teams',
        ),
    ]
