# Generated by Django 3.1.3 on 2021-02-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210210_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='configcontroller',
            name='competition_email_time_to_repeat',
            field=models.IntegerField(default=1800),
        ),
    ]
