# Generated by Django 3.1.3 on 2021-01-29 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210127_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffcustomteams',
            name='team_captain_email',
            field=models.EmailField(default='no@email.com', max_length=254),
        ),
    ]
