# Generated by Django 3.1.3 on 2020-12-21 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_staffcustomcompetition_competition_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffcustomcompetition',
            name='competition_banner',
            field=models.URLField(default='https://cdn1.dotesports.com/wp-content/uploads/2019/12/16125403/cod38.jpg', max_length=1000),
        ),
    ]
