# Generated by Django 3.1.3 on 2020-12-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201221_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffcustomcompetition',
            name='competition_type',
            field=models.CharField(choices=[('SQUAD', 'squad'), ('TRIOS', 'trios'), ('DUOS', 'duos'), ('SOLOS', 'solos')], default='SQUAD', max_length=5),
        ),
    ]
