# Generated by Django 3.1.3 on 2021-01-29 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_staffcustomteams_team_captain_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffcustomteams',
            name='team_captain_email',
        ),
    ]
