# Generated by Django 3.1.3 on 2021-01-30 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_staffcustomteams_team_captain_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffcustomteams',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='core.staffcustomcompetition'),
        ),
    ]
