# Generated by Django 3.1.3 on 2020-12-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_staffcustomcompetition_competition_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffcustomcompetition',
            name='competition_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='staffcustomcompetition',
            name='competition_type',
            field=models.CharField(choices=[('SQUADS', 'SQUADS'), ('TRIOS', 'TRIOS'), ('DUOS', 'DUOS'), ('SOLOS', 'SOLOS')], max_length=6),
        ),
    ]
