# Generated by Django 3.1.3 on 2020-12-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20201222_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffcustomteams',
            name='data_to_render',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
