# Generated by Django 3.1.3 on 2021-01-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210130_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffcustomteams',
            name='team_captain_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
