# Generated by Django 3.1.3 on 2021-02-12 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_match_match_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='damage_done',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='kd',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='kills',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='placement',
            field=models.IntegerField(null=True),
        ),
    ]
