# Generated by Django 3.1.3 on 2021-01-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_staffcustomteams_team_captain_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffcustomteams',
            name='total_teams_allowed_to_compete',
            field=models.IntegerField(null=True),
        ),
    ]
