# Generated by Django 3.1.3 on 2021-02-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210212_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='user_id_type',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
