# Generated by Django 3.1.3 on 2020-12-26 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_staffcustomteams_data_to_render'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffcustomteams',
            name='data_to_score',
        ),
    ]
