# Generated by Django 3.1.3 on 2021-01-31 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_staffcustomteams_total_teams_allowed_to_compete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffcustomteams',
            name='total_teams_allowed_to_compete',
        ),
        migrations.AddField(
            model_name='staffcustomcompetition',
            name='total_teams_allowed_to_compete',
            field=models.IntegerField(null=True),
        ),
    ]
