# Generated by Django 3.1.3 on 2021-02-12 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_match_user_id_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competition', to='core.staffcustomcompetition'),
        ),
    ]
