# Generated by Django 3.1.3 on 2020-12-26 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_staffcustomteams_data_to_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffcustomcompetition',
            name='points_per_first_place',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='staffcustomcompetition',
            name='points_per_second_place',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='staffcustomcompetition',
            name='points_per_third_place',
            field=models.IntegerField(default=3),
        ),
    ]
