# Generated by Django 3.1.3 on 2021-02-12 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_match_competition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='core.staffcustomteams'),
        ),
    ]
