# Generated by Django 3.1.3 on 2021-01-31 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210131_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffcustomcompetition',
            name='discord_link',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='staffcustomcompetition',
            name='facebook_link',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='staffcustomcompetition',
            name='instagram_link',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='staffcustomcompetition',
            name='twitch_link',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='staffcustomcompetition',
            name='twitter_link',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
