# Generated by Django 3.1.3 on 2020-12-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20201226_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffcustomcompetition',
            name='number_of_matches_to_count_points',
            field=models.IntegerField(default=5),
        ),
    ]
