# Generated by Django 3.1.3 on 2021-02-12 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210212_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='damage_taken',
            field=models.FloatField(null=True),
        ),
    ]
