# Generated by Django 3.1.3 on 2021-01-31 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210131_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffcustomcompetition',
            name='discord_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='staffcustomcompetition',
            name='facebook_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='staffcustomcompetition',
            name='instagram_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='staffcustomcompetition',
            name='twitch_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='staffcustomcompetition',
            name='twitter_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
