# Generated by Django 3.1.3 on 2021-01-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210131_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffcustomcompetition',
            name='total_teams_allowed_to_compete',
            field=models.IntegerField(default=30, null=True),
        ),
    ]
