# Generated by Django 3.1.3 on 2021-02-13 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_match_damage_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.staffcustomteams'),
        ),
    ]
