# Generated by Django 3.1.3 on 2021-02-13 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210213_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='user_idd',
            new_name='user_id',
        ),
    ]
