# Generated by Django 3.1.3 on 2021-02-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210213_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='match',
            name='user_id_type',
        ),
        migrations.AddField(
            model_name='player',
            name='user_id_type',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
