# Generated by Django 3.1.3 on 2021-02-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20210213_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='user_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='user_id_type',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
