# Generated by Django 3.1.3 on 2021-02-13 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20210213_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='match',
            name='user_id_type',
        ),
    ]
