# Generated by Django 3.1.3 on 2021-02-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20210213_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='deaths',
            field=models.IntegerField(null=True),
        ),
    ]
