# Generated by Django 3.1.3 on 2021-02-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_match_deaths'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='headshots',
            field=models.IntegerField(null=True),
        ),
    ]
