# Generated by Django 3.1.3 on 2021-02-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_match_headshots'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anlytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_of_warzone_api_requests_completed', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Duelout Analytics',
                'verbose_name_plural': 'Duelout Analytics',
            },
        ),
    ]
