# Generated by Django 3.1.3 on 2021-02-17 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_anlytics'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Anlytics',
            new_name='Analytics',
        ),
    ]
