# Generated by Django 3.1.3 on 2021-02-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20210217_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analytics',
            options={'verbose_name': 'Application Analytics', 'verbose_name_plural': 'Application Analytics'},
        ),
        migrations.AddField(
            model_name='analytics',
            name='name',
            field=models.CharField(default='main_analytics', max_length=100, null=True, unique=True),
        ),
    ]
