# Generated by Django 3.1.3 on 2021-02-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20210217_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffcustomcompetition',
            name='points_per_fifth_place',
            field=models.IntegerField(default=0, verbose_name='Points for placing - 5th Place'),
        ),
        migrations.AddField(
            model_name='staffcustomcompetition',
            name='points_per_fourth_place',
            field=models.IntegerField(default=0, verbose_name='Points for placing - 4th Place'),
        ),
    ]
