# Generated by Django 3.1.3 on 2021-02-17 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20210217_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analytics',
            old_name='amount_of_warzone_api_requests_completed',
            new_name='amount_of_warzone_api_requests_calls',
        ),
        migrations.RemoveField(
            model_name='analytics',
            name='name',
        ),
        migrations.AddField(
            model_name='analytics',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
