# Generated by Django 3.1.3 on 2021-02-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20210217_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffcustomteams',
            name='team_stream_user_type',
            field=models.CharField(choices=[('twitch', 'Twitch'), ('facebook', 'Facebook'), ('youtube', 'Youtube')], default='twitch', max_length=10),
        ),
        migrations.AlterField(
            model_name='staffcustomcompetition',
            name='total_teams_allowed_to_compete',
            field=models.IntegerField(default=20, null=True),
        ),
    ]
