# Generated by Django 3.1.3 on 2021-02-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20210218_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffcustomteams',
            name='team_stream_user_type',
            field=models.CharField(choices=[('twitch', 'Twitch'), ('facebook', 'Facebook'), ('youtube', 'Youtube')], default='twitch', max_length=10, null=True),
        ),
    ]
