# Generated by Django 3.1.3 on 2021-02-18 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20210218_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffcustomteams',
            old_name='team_twitch_stream_user',
            new_name='team_stream_user',
        ),
    ]
