# Generated by Django 3.1.3 on 2021-02-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_staffcustomcompetition_competition_cover_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, null=True)),
                ('user_id_type', models.CharField(choices=[('battle', 'Battlenet ID'), ('psn', 'Psnet ID'), ('xbl', 'XboxLive ID')], default='battle', max_length=10)),
            ],
        ),
    ]
