# Generated by Django 3.1.3 on 2021-03-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_playerverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffcustomcompetition',
            name='calculate_scores_once_job_active',
            field=models.BooleanField(default=False),
        ),
    ]
