# Generated by Django 3.1.3 on 2021-03-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_staffcustomcompetition_calculate_scores_once_job_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffcustomcompetition',
            name='calculate_scores_once_job_active',
            field=models.CharField(choices=[('Started', 'Started'), ('In-Progress', 'In-Progress'), ('Completed', 'Completed')], max_length=11),
        ),
    ]
