# Generated by Django 3.1.3 on 2021-03-07 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20210307_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffcustomcompetition',
            old_name='calculate_scores_once_job_active',
            new_name='manually_calculate_bg_job_status',
        ),
    ]
