# Generated by Django 3.1.3 on 2021-03-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20210307_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffcustomcompetition',
            name='manually_calculate_bg_job_status',
            field=models.CharField(choices=[('Started', 'Started'), ('In-Progress', 'In-Progress'), ('Completed', 'Completed')], default='Completed', max_length=11),
        ),
    ]
