# Generated by Django 3.1.3 on 2021-03-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20210308_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffcustomcompetition',
            name='competition_status',
            field=models.CharField(choices=[('Not-Started', 'Not-Started'), ('In-Progress', 'In-Progress'), ('Ended', 'Ended')], default='Not-Started', max_length=20),
        ),
    ]
