# Generated by Django 3.1.3 on 2021-03-14 17:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20210308_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffcustomcompetition',
            name='competition_entry',
            field=models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], default='Free', max_length=5),
        ),
        migrations.AddField(
            model_name='staffcustomcompetition',
            name='competition_password',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
