# Generated by Django 3.1.3 on 2021-03-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20210314_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffcustomcompetition',
            name='competition_password',
            field=models.CharField(default='warz0ne4ever', max_length=15),
        ),
    ]
