# Generated by Django 3.1.3 on 2021-03-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20210314_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffcustomcompetition',
            name='competition_password',
            field=models.CharField(default='easy012pass', max_length=15),
        ),
    ]
