# Generated by Django 3.1.3 on 2021-03-15 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_abstractmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastTournaments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('total_participants', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Past Tournament',
                'verbose_name_plural': 'Past Tournaments',
            },
        ),
        migrations.CreateModel(
            name='PastTeams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('data', models.JSONField()),
                ('points', models.IntegerField()),
                ('tournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PastTeams', to='core.pasttournaments')),
            ],
            options={
                'verbose_name': 'Past Team',
                'verbose_name_plural': 'Past Teams',
            },
        ),
    ]
