# Generated by Django 3.1.3 on 2021-03-15 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_pastteams_pasttournaments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pasttournaments',
            old_name='total_participants',
            new_name='total_teams',
        ),
    ]
