# Generated by Django 3.1.3 on 2021-03-15 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20210315_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastteams',
            name='data',
        ),
    ]
