# Generated by Django 3.1.3 on 2021-03-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_remove_pastteams_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastteams',
            name='data',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='pastteams',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='pasttournaments',
            name='logo',
            field=models.URLField(default=''),
        ),
    ]
