# Generated by Django 3.1.3 on 2021-03-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_auto_20210315_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastteams',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
