# Generated by Django 3.1.3 on 2021-03-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20210315_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasttournaments',
            name='logo',
            field=models.URLField(),
        ),
    ]
