# Generated by Django 3.1.3 on 2021-03-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20210315_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasttournaments',
            name='host',
            field=models.CharField(default='', max_length=100),
        ),
    ]
