# Generated by Django 3.1.3 on 2021-03-15 21:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_pasttournaments_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasttournaments',
            name='date_ended',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
