# Generated by Django 3.1.3 on 2021-03-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_pasttournaments_date_ended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastteams',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='pasttournaments',
            name='host',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='pasttournaments',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
