# Generated by Django 3.1.3 on 2021-03-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_auto_20210315_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='configcontroller',
            name='system_message',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pastteams',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pasttournaments',
            name='logo',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='pasttournaments',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
