# Generated by Django 3.1.3 on 2021-03-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_auto_20210324_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='configcontroller',
            name='system_message_type',
            field=models.CharField(choices=[('WARNING', 'Warning'), ('INFO', 'Info')], default='Info', max_length=10),
        ),
        migrations.AlterField(
            model_name='configcontroller',
            name='system_message',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
    ]
