# Generated by Django 3.1.3 on 2021-03-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_auto_20210324_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configcontroller',
            name='system_message_type',
            field=models.CharField(choices=[('warning', 'Warning'), ('info', 'Info')], default='Info', max_length=10),
        ),
    ]
