# Generated by Django 3.1.3 on 2021-03-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_auto_20210324_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configcontroller',
            name='system_message_type',
            field=models.CharField(choices=[('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info')], default='Info', max_length=10),
        ),
    ]
