# Generated by Django 3.1.3 on 2021-03-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_auto_20210324_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configcontroller',
            name='system_message',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
