# Generated by Django 3.1.3 on 2021-03-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_auto_20210324_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffcustomcompetition',
            name='manually_calculate_bg_job_status',
            field=models.CharField(choices=[('Started', 'Started'), ('In-Progress', 'In-Progress'), ('Completed', 'Completed'), ('Not-Running', 'Not-Running')], default='Not-Running', max_length=12),
        ),
    ]
