# Generated by Django 3.1.3 on 2021-03-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_auto_20210328_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffcustomteams',
            name='errors',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
