# Generated by Django 3.1.3 on 2021-03-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_staffcustomteams_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffcustomteams',
            name='player_2_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='staffcustomteams',
            name='player_3_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='staffcustomteams',
            name='player_4_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='staffcustomcompetition',
            name='manually_calculate_bg_job_status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Started', 'Started'), ('In-Progress', 'In-Progress'), ('Completed', 'Completed'), ('Not-Running', 'Not-Running')], default='Scheduled', max_length=12),
        ),
        migrations.AlterField(
            model_name='staffcustomteams',
            name='team_stream_user_type',
            field=models.CharField(choices=[('twitch', 'Twitch'), ('facebook', 'Facebook')], default='twitch', max_length=10, null=True),
        ),
    ]
