# Generated by Django 3.1.3 on 2021-03-30 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_auto_20210330_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pastteams',
            old_name='email',
            new_name='email_captain',
        ),
        migrations.AddField(
            model_name='pastteams',
            name='player_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pastteams',
            name='player_1_id_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pastteams',
            name='player_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pastteams',
            name='player_2_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='pastteams',
            name='player_2_id_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pastteams',
            name='player_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pastteams',
            name='player_3_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='pastteams',
            name='player_3_id_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pastteams',
            name='player_4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pastteams',
            name='player_4_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='pastteams',
            name='player_4_id_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
