# Generated by Django 3.1.3 on 2021-03-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_auto_20210330_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastteams',
            name='email_captain',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='pastteams',
            name='player_2_email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='pastteams',
            name='player_3_email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='pastteams',
            name='player_4_email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
    ]
