# Generated by Django 3.1.3 on 2021-03-30 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_auto_20210330_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastteams',
            name='data',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
