# Generated by Django 3.1.3 on 2021-03-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_auto_20210330_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffcustomteams',
            name='player_2_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='staffcustomteams',
            name='player_3_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='staffcustomteams',
            name='player_4_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
