# Generated by Django 3.1.3 on 2021-04-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_auto_20210331_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team_wipes',
            field=models.IntegerField(null=True),
        ),
    ]
