# Generated by Django 3.1.3 on 2021-04-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_match_team_wipes'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='longest_streak',
            field=models.IntegerField(null=True),
        ),
    ]
