# Generated by Django 3.1.3 on 2021-04-02 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_match_percent_time_moving'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='duration',
            new_name='time_played',
        ),
    ]
