# Generated by Django 3.1.3 on 2021-04-02 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_auto_20210402_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffcustomteams',
            name='player_1_kd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffcustomteams',
            name='player_2_kd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffcustomteams',
            name='player_3_kd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffcustomteams',
            name='player_4_kd',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
