# Generated by Django 3.1.3 on 2021-04-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_auto_20210402_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='user_kd',
            field=models.FloatField(null=True),
        ),
    ]
