# Generated by Django 3.1.3 on 2021-04-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_player_user_kd'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='player_kd_at_time',
            field=models.FloatField(null=True),
        ),
    ]
