# Generated by Django 3.1.3 on 2021-04-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_match_player_kd_at_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='user_kd',
            field=models.FloatField(default=0),
        ),
    ]
