# Generated by Django 3.1.3 on 2021-04-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_auto_20210403_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='user_kd',
            field=models.FloatField(null=True),
        ),
    ]
