# Generated by Django 3.1.3 on 2021-04-04 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_auto_20210404_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='core.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='core.staffcustomteams'),
        ),
        migrations.AlterField(
            model_name='player',
            name='competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='core.staffcustomcompetition'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='core.staffcustomteams'),
        ),
    ]
