# Generated by Django 3.1.3 on 2021-04-04 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_auto_20210404_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastteams',
            name='data',
        ),
    ]
