# Generated by Django 3.1.3 on 2021-04-07 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_remove_pastteams_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configcontroller',
            old_name='competition_email_time_to_repeat',
            new_name='competition_email_time_before_start',
        ),
    ]
