# Generated by Django 3.1.3 on 2021-04-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_auto_20210407_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='configcontroller',
            name='competition_close_inscriptions_bg_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staffcustomteams',
            name='close_inscriptions_started',
            field=models.BooleanField(default=False),
        ),
    ]
