# Generated by Django 3.1.3 on 2021-04-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_auto_20210407_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='configcontroller',
            name='competition_close_inscriptions_before_start',
            field=models.IntegerField(default=1800),
        ),
    ]
