# Generated by Django 3.1.3 on 2021-04-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_configcontroller_competition_close_inscriptions_before_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffcustomteams',
            name='close_inscriptions_started',
        ),
        migrations.AddField(
            model_name='staffcustomcompetition',
            name='close_inscriptions_started',
            field=models.BooleanField(default=False),
        ),
    ]
