# Generated by Django 3.1.3 on 2021-04-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_auto_20210407_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffcustomcompetition',
            name='model_rank',
            field=models.CharField(choices=[('Gold', 'Gold'), ('Platinum', 'Platinum'), ('Master', 'Master'), ('Legend', 'Legend')], default='Gold', max_length=8),
        ),
    ]
