# Generated by Django 3.1.3 on 2021-04-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_staffcustomcompetition_model_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffcustomcompetition',
            name='model_rank',
            field=models.CharField(choices=[('Gold', 'Gold'), ('Platinum', 'Platinum'), ('Master', 'Master'), ('Legend', 'Legend'), ('Catch_all', 'Catch all')], default='Gold', max_length=9),
        ),
    ]
