# Generated by Django 3.1.3 on 2021-04-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_auto_20210412_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='anomalous_match',
            field=models.BooleanField(null=True),
        ),
    ]
