# Generated by Django 3.1.3 on 2021-04-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_match_anomalous_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
