# Generated by Django 3.1.3 on 2021-04-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_match_match_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='configcontroller',
            name='anomaly_detection_active',
            field=models.BooleanField(default=True),
        ),
    ]
