# Generated by Django 3.1.3 on 2021-04-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_configcontroller_anomaly_detection_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='RocketLeague',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=150, null=True, unique=True)),
                ('captain_name', models.CharField(max_length=100, null=True)),
                ('captain_cellphone_number', models.CharField(max_length=100, null=True)),
                ('captain_email', models.EmailField(max_length=254)),
                ('player_1_id', models.CharField(max_length=200, null=True, unique=True)),
                ('player_1_platform', models.CharField(choices=[('PC', 'PC'), ('PSN', 'PSN'), ('XBOX', 'XBOX')], max_length=5)),
                ('player_1_rank', models.CharField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Platinum', 'Platinum'), ('Diamond', 'Diamond'), ('Champion', 'Champion'), ('Grand Champion', 'Grand Champion')], max_length=50)),
                ('player_2_id', models.CharField(max_length=200, null=True, unique=True)),
                ('player_2_platform', models.CharField(choices=[('PC', 'PC'), ('PSN', 'PSN'), ('XBOX', 'XBOX')], max_length=5)),
                ('player_2_rank', models.CharField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Platinum', 'Platinum'), ('Diamond', 'Diamond'), ('Champion', 'Champion'), ('Grand Champion', 'Grand Champion')], max_length=50)),
                ('player_3_id', models.CharField(max_length=200, null=True, unique=True)),
                ('player_3_platform', models.CharField(choices=[('PC', 'PC'), ('PSN', 'PSN'), ('XBOX', 'XBOX')], max_length=5)),
                ('player_3_rank', models.CharField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Platinum', 'Platinum'), ('Diamond', 'Diamond'), ('Champion', 'Champion'), ('Grand Champion', 'Grand Champion')], max_length=50)),
            ],
            options={
                'verbose_name': 'Rocket League Team',
                'verbose_name_plural': 'Rocket League Teams',
            },
        ),
    ]
