# Generated by Django 3.1.3 on 2021-04-26 22:47

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_auto_20210416_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('warzone_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('stream_url', models.URLField()),
            ],
        ),
    ]
