# Generated by Django 3.1.3 on 2021-04-27 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_auto_20210427_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_name',
        ),
    ]
