# Generated by Django 3.1.3 on 2021-04-27 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_remove_profile_profile_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
