# Generated by Django 3.1.3 on 2021-04-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_auto_20210427_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(to='core.Profile'),
        ),
    ]
