# Generated by Django 3.1.3 on 2021-04-27 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_auto_20210427_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='description',
        ),
    ]
