# Generated by Django 3.1.3 on 2021-04-27 22:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_remove_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='invite_code',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
