# Generated by Django 3.1.3 on 2021-04-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_team_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='invite_code',
            field=models.UUIDField(default='28253D'),
        ),
    ]
