# Generated by Django 3.1.3 on 2021-04-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_auto_20210427_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='invite_code',
            field=models.CharField(default='C719D2', max_length=50),
        ),
    ]
