# Generated by Django 3.1.3 on 2021-04-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_auto_20210427_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='invite_code',
            field=models.CharField(default='B973A4', max_length=50),
        ),
    ]
