# Generated by Django 3.1.3 on 2021-04-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_auto_20210427_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regiments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(max_length=250)),
                ('invite_code', models.CharField(default='62DEBB', max_length=50)),
                ('test', models.CharField(max_length=50, null=True)),
                ('members', models.ManyToManyField(to='core.Profile')),
            ],
            options={
                'verbose_name': 'Regiment',
                'verbose_name_plural': 'Regiments',
            },
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
