# Generated by Django 3.1.3 on 2021-04-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_auto_20210427_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regiment',
            name='test',
        ),
        migrations.AlterField(
            model_name='regiment',
            name='invite_code',
            field=models.CharField(default='3F2FED', max_length=50),
        ),
    ]
