# Generated by Django 3.1.3 on 2021-04-28 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_auto_20210427_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='regiment',
            name='leader',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader', to='core.profile'),
        ),
        migrations.AlterField(
            model_name='regiment',
            name='invite_code',
            field=models.CharField(default='292DBF', max_length=50),
        ),
        migrations.AlterField(
            model_name='regiment',
            name='members',
            field=models.ManyToManyField(related_name='members', to='core.Profile'),
        ),
    ]
