# Generated by Django 3.1.3 on 2021-04-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0118_auto_20210428_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regiment',
            name='invite_code',
            field=models.CharField(default='241EF7', max_length=50),
        ),
        migrations.AlterField(
            model_name='regiment',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members', to='core.Profile'),
        ),
    ]
