# Generated by Django 3.1.3 on 2021-04-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_auto_20210428_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regiment',
            name='invite_code',
            field=models.CharField(default='516BDB', max_length=50),
        ),
    ]
