# Generated by Django 3.1.3 on 2021-04-28 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_auto_20210428_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regiment',
            name='invite_code',
            field=models.CharField(default='6407E2', max_length=50),
        ),
        migrations.AlterField(
            model_name='regiment',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader', to='core.profile'),
        ),
    ]
