# Generated by Django 3.1.3 on 2021-04-28 14:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_auto_20210428_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regiment',
            name='invite_code',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
