# Generated by Django 3.1.3 on 2021-04-28 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0122_auto_20210428_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regiment',
            name='invite_code',
        ),
    ]
