# Generated by Django 3.1.3 on 2021-04-28 14:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0123_remove_regiment_invite_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='regiment',
            name='invite_code',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
