# Generated by Django 3.1.3 on 2021-04-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0125_auto_20210428_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='warzone_tag_verified',
            field=models.BooleanField(default=False),
        ),
    ]
