# Generated by Django 3.1.3 on 2021-04-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0126_profile_warzone_tag_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='warzone_tag_error_message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
