# Generated by Django 3.1.3 on 2021-04-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0127_profile_warzone_tag_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='warzone_tag_type',
            field=models.CharField(choices=[('battle', 'Battlenet ID'), ('psn', 'Psnet ID'), ('xbl', 'XboxLive ID')], default='battle', max_length=50),
        ),
    ]
