# Generated by Django 3.1.3 on 2021-05-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0128_profile_warzone_tag_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='https://play-lh.googleusercontent.com/r2-_2oE9tU_46_n4GIC21PmqNIqPMoQNRPhfVNnK1v8hmDfA_yLuRwCy_E1cf5Wh4oM', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='warzone_tag',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='warzone_tag_error_message',
            field=models.CharField(blank=True, default='None', max_length=200, null=True),
        ),
    ]
