# Generated by Django 3.1.3 on 2021-05-04 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0132_auto_20210502_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='regiment',
            name='regiment_logo',
            field=models.ImageField(default='', null=True, upload_to='profile_pics'),
        ),
    ]
