# Generated by Django 3.1.3 on 2021-05-04 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0134_auto_20210504_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='https://play-lh.googleusercontent.com/r2-_2oE9tU_46_n4GIC21PmqNIqPMoQNRPhfVNnK1v8hmDfA_yLuRwCy_E1cf5Wh4oM', null=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='regiment',
            name='regiment_logo',
            field=models.ImageField(default='https://play-lh.googleusercontent.com/r2-_2oE9tU_46_n4GIC21PmqNIqPMoQNRPhfVNnK1v8hmDfA_yLuRwCy_E1cf5Wh4oM', null=True, upload_to='regiment_pics'),
        ),
    ]
