# Generated by Django 3.1.3 on 2021-05-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0135_auto_20210504_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='profile_pics/default.png', null=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='regiment',
            name='regiment_logo',
            field=models.ImageField(default='regiment_pics/default.png', null=True, upload_to='regiment_pics'),
        ),
    ]
