# Generated by Django 3.1.3 on 2021-05-05 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0136_auto_20210505_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True, unique=True)),
                ('player_1', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_1', to='core.profile')),
                ('player_2', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_2', to='core.profile')),
                ('player_3', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_3', to='core.profile')),
                ('player_4', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_4', to='core.profile')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
    ]
