# Generated by Django 3.1.3 on 2021-05-05 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0137_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='player_1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_1', to='core.profile'),
        ),
        migrations.AlterField(
            model_name='team',
            name='player_2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_2', to='core.profile'),
        ),
        migrations.AlterField(
            model_name='team',
            name='player_3',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_3', to='core.profile'),
        ),
        migrations.AlterField(
            model_name='team',
            name='player_4',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_4', to='core.profile'),
        ),
    ]
