# Generated by Django 3.1.3 on 2021-04-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=15)),
                ('kills', models.IntegerField()),
                ('record_mode', models.CharField(choices=[('Solos', 'Solos'), ('Duos', 'Duos'), ('Trios', 'Trios'), ('Squads', 'Squads')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ManyToManyField(related_name='teams', to='leaderboards.Teams')),
            ],
        ),
    ]
