# Generated by Django 3.1.3 on 2021-04-25 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teams',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.DeleteModel(
            name='Records',
        ),
    ]
